{-# LANGUAGE RecordWildCards #-}
import Sprockell.System

prog :: [Instruction]
prog = [

     Const 2 RegA,
     Store RegA (Addr 0),
     Const 2 RegA,
     Store RegA (Addr 1),
     Const 3 RegA,
     Store RegA (Addr 2),
     Const 0 RegA,
     Const 0 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 1 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 2 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Store RegA (Addr 3),
     Load (Addr 3) RegA,
     Const 3 RegB,
     Compute Lt RegA RegB RegA,
     Branch RegA (Rel (2)),
     Jump (Rel (16)),
     Const 0 RegA,
     Load (Addr 3) RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Const 2 RegB,
     Compute Mul RegA RegB RegA,
     Const 0 RegB,
     Load (Addr 3) RegC,
     Compute Add RegB RegC RegC,
     Store RegA (Deref RegC),
     Load (Addr 3) RegA,
     Const 1 RegB,
     Compute Add RegA RegB RegA,
     Store RegA (Addr 3),
     Jump (Rel (-19)),
     Const 0 RegA,
     Const 0 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 1 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 2 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 0 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Const 0 RegB,
     Const 1 RegC,
     Compute Add RegB RegC RegC,
     Load (Deref RegC) RegB,
     Compute Equal RegA RegB RegA,
     Write RegA stdio,
     Const 0 RegA,
     Const 0 RegB,
     Compute Add RegA RegB RegB,
     Load (Deref RegB) RegA,
     Const 0 RegB,
     Const 2 RegC,
     Compute Add RegB RegC RegC,
     Load (Deref RegC) RegB,
     Compute Equal RegA RegB RegA,
     Write RegA stdio,
     Nop,
     EndProg
        ]

main :: IO()
main = do
  putStr "###BEGIN###"
  _ <- run 1 prog
  putStr "###END###\n"
  return ()


